//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Konum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Konum()
        {
            this.Tbl_Kullanici = new HashSet<Tbl_Kullanici>();
        }
    
        public int KonumId { get; set; }
        public Nullable<decimal> Enlem { get; set; }
        public Nullable<decimal> Boylam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Kullanici> Tbl_Kullanici { get; set; }
    }
}
